export const postUrls = ["https://samperalabs.com/posts/how-to-handle-human-in-the-loop-with-langgraph-and-fastapi",
"https://samperalabs.com/posts/create-a-chatbot-part-4-adding-memory-to-the-graph",
"https://samperalabs.com/posts/create-a-chatbot-part-3-using-assistant-ui-and-react-to-handle-the-backend-endpoints",
"https://samperalabs.com/posts/create-a-chatbot-part-2-creating-the-fastapi-endpoints",
"https://samperalabs.com/posts/how-to-create-a-chatbot-with-langgraph-fastapi-and-react-part-1",
"https://samperalabs.com/posts/set-up-ruff-and-uv-for-python-projects",
"https://samperalabs.com/posts/analyzing-open-deep-research",
"https://samperalabs.com/posts/creating-custom-tools-in-langgraph",
"https://samperalabs.com/posts/basic-langgraph-chatbot-with-memory",
"https://samperalabs.com/posts/register-domain-with-cloudflare-and-deploy-it-to-coolify",
"https://samperalabs.com/posts/uv-a-package-manager-coming-to-replace-pip",
"https://samperalabs.com/posts/how-to-manage-sqlite-databases-on-a-vps-with-coolify",
"https://samperalabs.com/posts/deploy-astro-website-to-coolify",
"https://samperalabs.com/posts/how-to-create-your-own-ocr-service-with-doctr-and-modal"]