site:
  name: samperalabs
  site: 'https://samperalabs.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId:

# Default SEO metadata
metadata:
  title:
    default: Bernat Sampera
    template: '%s — Bernat Sampera'
  description: 'Builder and writer at the intersection of AI and software.'
  robots:
    index: true
    follow: true
  openGraph:
    site_name: samperalabs
    images:
      - url: '~/assets/images/default.png'
        width: 1200
        height: 628
    type: website
  twitter:
    handle: '@bernatsampera'
    site: '@samperalabs'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"
