const essays = [
  { id:'tree', topic:'context', label:'AI context', time:'2 min', title:'Give your agent a map of your business.', summary:'How a context tree helps an agent find the right files for a support task.', flow:['Task','Context','Answer'], takeaway:'Organize the knowledge once. Let the agent follow the links for each task.', detail:'This post shows how support work at MAAT moved from manual steps to a context tree. The tree links to payment information, database details, and task instructions.', original:'How we built a context tree for our agent to resolve support tasks', url:'https://samperalabs.com/posts/context-tree-agent-support-tasks' },
  { id:'repo', topic:'context', label:'AI context', time:'5 min', title:'Stop explaining your setup in every chat.', summary:'Keep what your agent needs to know in its own versioned repository.', flow:['Know it','Save it','Reuse it'], takeaway:'Treat context as a thing you can edit, organize, and version.', detail:'A separate repository gives your agent a stable record of your tools, processes, and decisions. Load the files the current task needs.', original:'Your AI Agent Deserves Its Own Repo', url:'https://samperalabs.com/posts/your-ai-agent-deserves-its-own-repo' },
  { id:'review', topic:'building', label:'Building agents', time:'9 min', title:'Give your agent a pause button.', summary:'Add human review to a LangGraph app before the answer goes out.', flow:['AI draft','Review','Continue'], takeaway:'Let the agent prepare the answer. Pause the flow for a person to check it.', detail:'A practical guide to a review step in LangGraph, a FastAPI backend, and a React interface. The person can accept or reject the answer before the workflow continues.', original:'How to handle Human in the loop with Langgraph and FastAPI', url:'https://samperalabs.com/posts/how-to-handle-human-in-the-loop-with-langgraph-and-fastapi' }
];
const products = {
  bjj:{name:'BJJGym',symbol:'b.',url:'https://bjjgym.com',caption:'Find a gym by city and training type.'},
  context:{name:'ContextAgora',symbol:'[c]',url:'https://contextagora.com',caption:'Choose what the agent knows for this task.'},
  pack:{name:'Pack den Sack',symbol:'p.',url:'https://samperalabs.com/posts/packdensack',caption:'Turn a trip into a useful packing list.'}
};
const state={product:'bjj',topic:'all',city:'Barcelona',style:'all',gym:0,modules:{docs:true,records:false},trip:'city',packed:new Set()};
const $=s=>document.querySelector(s);
const announce=text=>{$('#announcement').textContent=text};
const gyms={
  Barcelona:[{name:'North Academy',area:'Gràcia',type:'gi',time:'18:30',x:35,y:23},{name:'Coast Grappling',area:'Poblenou',type:'nogi',time:'19:00',x:67,y:62},{name:'Central BJJ',area:'Eixample',type:'gi',time:'20:00',x:42,y:53}],
  Lisbon:[{name:'River Academy',area:'Alcântara',type:'nogi',time:'18:00',x:30,y:57},{name:'Hill Grappling',area:'Graça',type:'gi',time:'19:30',x:64,y:25},{name:'West BJJ',area:'Campo de Ourique',type:'nogi',time:'20:00',x:37,y:32}],
  Berlin:[{name:'East Academy',area:'Friedrichshain',type:'gi',time:'18:00',x:64,y:42},{name:'Canal Grappling',area:'Kreuzberg',type:'nogi',time:'19:00',x:38,y:64},{name:'North BJJ',area:'Mitte',type:'gi',time:'20:30',x:33,y:20}]
};
const trips={city:{label:'City weekend',mark:'▦',description:'3 days · Light travel',items:['3 tops','Spare trousers','Walking shoes','Toiletries','Phone charger','Travel documents']},hike:{label:'Mountain hike',mark:'△',description:'2 days · Cool weather',items:['Base layer','Rain jacket','Walking boots','Water bottle','First aid kit','Trail map']},beach:{label:'Beach break',mark:'☼',description:'5 days · Warm weather',items:['Swimwear','Light clothes','Sun hat','Sunscreen','Beach towel','Sandals']}};
function renderEssays(){
  $('#essay-list').innerHTML=essays.filter(e=>state.topic==='all'||e.topic===state.topic).map(e=>`<button class="essay" data-essay="${e.id}"><span class="essay-meta"><span>${e.label}</span><span>${e.time}</span></span><h3>${e.title}</h3><p>${e.summary}</p><span class="essay-foot"><span class="mini-diagram">${e.flow.map(f=>`<i>${f}</i>`).join('<span>›</span>')}</span><span aria-hidden="true">↗</span></span></button>`).join('');
  document.querySelectorAll('[data-topic]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.topic===state.topic)));
}
function productTop(){const p=products[state.product];return `<div class="product-top"><div class="product-logo"><span class="product-symbol ${state.product}-symbol">${p.symbol}</span>${p.name}</div><span class="demo-badge">INTERACTIVE PREVIEW</span></div>`}
function heading(title,description){const p=products[state.product];return `<div class="product-heading"><div><h3>${title}</h3><p>${description}</p></div><a class="real-link" href="${p.url}" target="_blank" rel="noreferrer">${state.product==='pack'?'Project details':'Open real product'} ↗</a></div>`}
function renderBjj(){
 const list=gyms[state.city].map((g,i)=>({...g,id:i})).filter(g=>state.style==='all'||g.type===state.style);
 if(!list.some(g=>g.id===state.gym))state.gym=list[0].id;
 const selected=gyms[state.city][state.gym];
 return `${productTop()}<div class="product-body">${heading('New city. Same love for BJJ.','Choose a city. Find somewhere to train.')}<div class="search-controls"><label class="select-wrap"><span>Where are you going?</span><select id="city" aria-label="Choose city">${Object.keys(gyms).map(c=>`<option ${c===state.city?'selected':''}>${c}</option>`).join('')}</select></label><div class="segmented" aria-label="Training type">${[['all','All'],['gi','Gi'],['nogi','No-gi']].map(([v,l])=>`<button data-style="${v}" aria-pressed="${v===state.style}">${l}</button>`).join('')}</div></div><div class="map-layout"><div class="map" aria-label="Sample gym locations"><svg viewBox="0 0 350 270" preserveAspectRatio="none" aria-hidden="true"><path d="M295-20Q200 100 360 165L380 300H400V-20" fill="#c9e0df"/><g stroke="#fdfdf6" stroke-width="13" fill="none"><path d="M-10 40 320 120M-10 120 290 200M40-10-10 220M120-10 42 300M202-10 103 300M280-10 173 300M-20 210 260 290"/></g><g stroke="#d6dcca" stroke-width="1" fill="none"><path d="M-10 40 320 120M-10 120 290 200M40-10-10 220M120-10 42 300M202-10 103 300M280-10 173 300M-20 210 260 290"/></g><path d="m186 115 31 8-11 34-31-9zM65 27l33 9-12 30-29-8z" fill="#c5d5b0"/></svg><span class="district" style="left:14%;top:42%">${state.city.toUpperCase()}</span>${list.map(g=>`<button class="pin" style="left:${g.x}%;top:${g.y}%" data-gym="${g.id}" aria-label="Select ${g.name}" aria-pressed="${state.gym===g.id}"><span>${g.id+1}</span></button>`).join('')}<span class="map-caption">ILLUSTRATIVE MAP</span></div><div class="gym-results">${list.map(g=>`<button class="gym-card" data-gym="${g.id}" aria-pressed="${state.gym===g.id}"><strong>${g.name}<span>↗</span></strong><small>${g.area} · ${g.type==='gi'?'Gi':'No-gi'} · ${g.time}</small></button>`).join('')}<div class="gym-detail"><b>${selected.name}</b><br>Sample class at ${selected.time}.<br>All gyms and times here are fictional.</div></div></div></div>`;
}
function renderContext(){
 const {docs,records}=state.modules;
 const response=docs&&records?'The sample account has an active payment, but the membership record is out of date. The support guide says to check the sync job next.':docs?'I found the support guide. It says to compare the payment with the membership record. Select sample records so I can check this case.':records?'The sample payment is active, but the membership record is out of date. Select the support guide so I can find the correct next step.':'I do not have the account details or the support process. What should I check?';
 const files=[docs?'support/guide.md':null,records?'records/sample-account.json':null].filter(Boolean);
 return `${productTop()}<div class="product-body">${heading('Same question. Better context.','Select the files. Watch the answer change.')}<div class="context-layout"><div class="module-list"><p class="micro-heading">Available context</p><label class="module"><input type="checkbox" data-module="docs" ${docs?'checked':''}><span><strong>Support guide</strong><small>How to check an account</small></span></label><label class="module"><input type="checkbox" data-module="records" ${records?'checked':''}><span><strong>Sample records</strong><small>Payment and membership</small></span></label></div><div class="context-output"><div class="prompt">Why is this member’s access blocked?</div><div class="agent-reply"><div class="agent-icon">[c] / agent</div><p>${response}</p><div class="loaded-files">${files.length?'Read: '+files.join('<br>Read: '):'No files selected'}</div></div></div></div><div class="context-result">${docs&&records?'2 sources connected. The next step is clear.':files.length+' of 2 sources selected. Part of the picture is missing.'}</div><p class="context-hint">Scripted example. No AI call. No account access.</p></div>`;
}
function renderPack(){const trip=trips[state.trip];return `${productTop()}<div class="product-body">${heading('A trip in mind. A bag ready.','Pick your trip. Check off what you need.')}<div class="trip-options" aria-label="Choose a trip">${Object.entries(trips).map(([id,t])=>`<button data-trip="${id}" aria-pressed="${state.trip===id}"><span aria-hidden="true">${t.mark}</span>${t.label}</button>`).join('')}</div><div class="packing-layout"><div class="suitcase-panel"><div class="suitcase" aria-hidden="true">${trip.items.map((_,i)=>`<span class="packed-item ${state.packed.has(i)?'done':''}"></span>`).join('')}</div><div class="packing-progress">${state.packed.size} / ${trip.items.length} packed</div></div><div><p class="micro-heading">${trip.description}</p><div class="packing-list">${trip.items.map((item,i)=>`<label><input type="checkbox" data-item="${i}" ${state.packed.has(i)?'checked':''}><span>${item}</span></label>`).join('')}</div></div></div><p class="pack-note">Sample list. The full product uses AI to help plan your packing.</p></div>`}
function renderProduct(focusSelector){
 const stage=$('#product-stage');stage.className='product-stage '+state.product+'-stage';stage.innerHTML=state.product==='bjj'?renderBjj():state.product==='context'?renderContext():renderPack();
 document.querySelectorAll('[data-product]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.product===state.product)));
 $('#stage-caption').textContent=products[state.product].caption;
 if(focusSelector)$(focusSelector)?.focus({preventScroll:true});
}
function renderView(){const focus=location.hash==='#work';document.body.classList.toggle('focus-work',focus);document.querySelectorAll('[data-view]').forEach(a=>{if(a.dataset.view===(focus?'work':'home'))a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('.intro h1').innerHTML=focus?'Don’t just look.<br><span>Try a little of each.</span>':'Things I’ve learned.<br><span>Things you can use.</span>';$('.intro p').innerHTML=focus?'Three products. Three small interactions.<br>Pick one and see what it does.':'I build tools for AI, travel, and everyday problems.<br>Read the idea. Try the result.';document.title=focus?'Bernat Sampera | Product playground':'Bernat Sampera | Read & try';}
function openDialog(label,content){$('#detail').classList.remove('phone-preview');$('#dialog-label').textContent=label;$('#dialog-content').innerHTML=content;$('#detail').showModal()}
function showEssay(id){const e=essays.find(e=>e.id===id);openDialog(e.label+' / '+e.time,`<h2>${e.title}</h2><p class="takeaway">${e.takeaway}</p><p>${e.detail}</p><p class="source">Published as: ${e.original}</p><a class="dialog-link" href="${e.url}" target="_blank" rel="noreferrer">Read the published post <span>↗</span></a><p><a class="source" href="index.html#post">See the approved post design ↗</a></p>`)}
document.addEventListener('click',e=>{
 const button=e.target.closest('button');if(!button)return;
 if(button.dataset.panel){document.body.classList.toggle('mobile-read',button.dataset.panel==='read');document.querySelectorAll('[data-panel]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));announce(button.dataset.panel==='read'?'Post summaries selected.':'Product previews selected.')}
 if(button.dataset.product){state.product=button.dataset.product;renderProduct();announce(products[state.product].name+' preview selected.')}
 if(button.dataset.topic){state.topic=button.dataset.topic;renderEssays();announce('Showing '+(state.topic==='all'?'all posts':button.textContent)+' in the sample selection.')}
 if(button.dataset.style){state.style=button.dataset.style;renderProduct(`[data-style="${state.style}"]`);announce('Training filter changed to '+button.textContent)}
 if(button.dataset.gym!==undefined){state.gym=Number(button.dataset.gym);renderProduct(`.gym-card[data-gym="${state.gym}"]`);announce(gyms[state.city][state.gym].name+' selected.')}
 if(button.dataset.trip){state.trip=button.dataset.trip;state.packed=new Set();renderProduct(`[data-trip="${state.trip}"]`);announce(trips[state.trip].label+' packing list ready.')}
 if(button.dataset.essay)showEssay(button.dataset.essay);
 if(button.dataset.action==='close')$('#detail').close();
 if(button.dataset.action==='phone'){openDialog('Phone preview / 390 px',`<iframe title="Phone preview of the site" src="playground.html?phone=1" width="390"></iframe>`);$('#detail').classList.add('phone-preview')}
 if(button.dataset.action==='about')openDialog('About Bernat',`<h2>I build software.<br>I write down what I learn.</h2><p>This site brings the two together. The posts explain the ideas. The product previews let you try them.</p><a class="dialog-link" href="https://samperalabs.com/about" target="_blank" rel="noreferrer">More about Bernat ↗</a>`);
 if(button.dataset.action==='notes')openDialog('Design direction / 02',`<h2>Understand first.<br>Explore next.</h2><ul><li>Read and Try are visible together on a wide screen.</li><li>Post cards lead with the value to the reader.</li><li>Each product has its own look and a useful interaction.</li><li>The portfolio gives the selected product more room.</li><li>On phones, Read and Try switch the same space between posts and products.</li></ul><p>The three demos run locally with sample data. They show the product idea. They are not live product sessions.</p><p>The article headlines are proposed summaries. The published titles remain in the detail view.</p><p><a class="source" href="https://bjjgym.com" target="_blank" rel="noreferrer">BJJGym source ↗</a> · <a class="source" href="https://samperalabs.com/posts/contextagora" target="_blank" rel="noreferrer">ContextAgora source ↗</a> · <a class="source" href="https://samperalabs.com" target="_blank" rel="noreferrer">Post and project sources ↗</a></p><p><a class="source" href="index.html#post">Approved post design ↗</a></p>`);
});
document.addEventListener('change',e=>{
 if(e.target.id==='city'){state.city=e.target.value;state.gym=0;renderProduct('#city');announce('Showing sample gyms in '+state.city)}
 if(e.target.dataset.module){const key=e.target.dataset.module;state.modules[key]=e.target.checked;renderProduct(`[data-module="${key}"]`);announce('Context updated. '+Object.values(state.modules).filter(Boolean).length+' files selected.')}
 if(e.target.dataset.item!==undefined){const id=Number(e.target.dataset.item);if(e.target.checked)state.packed.add(id);else state.packed.delete(id);renderProduct(`[data-item="${id}"]`);announce(state.packed.size+' of '+trips[state.trip].items.length+' items packed.')}
});
$('#detail').addEventListener('click',e=>{if(e.target===$('#detail')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)e.target.close()}});
window.addEventListener('hashchange',()=>{renderView();window.scrollTo({top:0,behavior:'instant'})});
renderEssays();renderProduct();renderView();
if(new URLSearchParams(location.search).has('phone'))document.querySelector('[data-action="phone"]').hidden=true;
